name: AzureVirtualNetwork
summary: This is a deployment of a Azure Virtual Network using Terraform.
description: Deploys an Azure Virtual Network with Terraform
templatePath: main.tf
runner: acroademoade.azurecr.io/my-terraform:1.7.4
parameters:
  - id: "vnet_suffix"
    name: "Vnet Name Suffix"
    description: "myVNET-<Vnet Name Suffix>"
    type: "string"
  - id: "location"
    name: "Azure Virtual Network Location"
    description: "Azure Virtual Network Location"
    type: "string"
    default: "1"
    allowed:
      - "northeurope"
      - "westeurope"
      - "francecentral"
  - id: "address_space"
    name: "Address Space, Commas separated"
    description: 'Address Space. Exemple: "172.16.0.0/12", "10.0.0.0/8"'
    type: "string"
