name: AzureVirtualNetwork
summary: This is a deployment of a Azure Virtual Network using Terraform.
description: Deploys an Azure Virtual Network with Terraform
templatePath: main.tf
runner: acroademoade.azurecr.io/my-terraform:1.7.4
parameters:
  - id: "location"
    name: "Azure Virtual Network Location"
    description: "Azure Virtual Network Location"
    type: "string"
    default: "1"
    allowed:
      - "northeurope"
      - "westeurope"
      - "francecentral"
  - id: "address_space"
    name: "CIDR Address Spaces"
    description: "Azure Virtual Network Location CIDR address spaces"
    type: "array"
